//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicFactory.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lable
    {
        public Lable()
        {
            this.Artists = new HashSet<Artist>();
        }
    
        public int LabelID { get; set; }
        public string LegalName { get; set; }
        public Nullable<int> Country { get; set; }
    
        public virtual ICollection<Artist> Artists { get; set; }
    }
}
