#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace MusicFactory.DataAccessModel_Sales	
{
	public partial class Salesbycountry
	{
		private string _countryName;
		public virtual string CountryName
		{
			get
			{
				return this._countryName;
			}
			set
			{
				this._countryName = value;
			}
		}
		
		private long _sales;
		public virtual long Sales
		{
			get
			{
				return this._sales;
			}
			set
			{
				this._sales = value;
			}
		}
		
		private int _year;
		public virtual int Year
		{
			get
			{
				return this._year;
			}
			set
			{
				this._year = value;
			}
		}
		
	}
}
#pragma warning restore 1591
